name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade p
        pip install pipenv==2022.11.5
        if [ -f Pipfile ]; then pipenv install fi
    - name: Test with pytest
      run: |
        pytest
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade p
        pip install pipenv==2022.11.5
        if [ -f Pipfile ]; then pipenv install fi
    - name: Check code formatting with Ruff
      run: |
        ruff format .
    - name: Run Ruff linter tools
      run: |
        ruff check .
